name: json_dart_mappable
description: A new Jaspr project
version: 0.0.1

environment:
  sdk: ^3.10.0

dependencies:
  jaspr: ^0.22.0
  jaspr_router: ^0.8.1
  highlight: ^0.7.0
  universal_web: ^1.1.1+1

dev_dependencies:
  build_runner: ^2.10.0
  build_web_compilers: ^4.4.6
  jaspr_builder: ^0.22.0
  jaspr_tailwind: ^0.3.5
  lints: ^5.0.0
  test: ^1.25.0

jaspr:
  mode: static
  flutter: plugins
